name: Main
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: flyway
        uses: joshuaavalon/flyway-action@master
        with:
          url: jdbc:postgresql://postgres:postgres@postgres:5432/postgres